using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Message
{
    [Serializable]
    public enum STATUS { LOGIN, GET_TABLE, ADD_STUDENT, ADD_ADMIN, ADD_INSTRUCTOR, GET_GROUPS, GET_PROJECT_BY_STUDENT, GET_EVENTS_BY_PROJECT,
        GET_GROUPS_BY_INSTRUCTOR, GET_PROJECT_BY_ID, GET_STUDENTS_NAME_BY_GROUP, CREATE_LABS, GET_SUBJECTS_BY_INSTRUCTOR_ID, GET_LABS_BY_INSTRUCTOR, ADD_EVENT,
        UPDATE_EVENT, GET_STUDENTS_ID_BY_PARENT, EDIT_LABS, ADD_GROUP, EDIT_GROUP, DELETE_GROUP, GET_SUBJECTS, ADD_SUBJECT, EDIT_SUBJECT, DELETE_SUBJECT,
        GET_STUDENTS, ADD_FILE, DELETE_FILE, GET_FILES, GET_STUDENT_FILES, GET_GROUP_BY_FACULTY, GET_SPECIALITIES, DELETE_SPECIALITY, ADD_SPECIALITY, EDIT_SPECIALITY, CREATE_RGR, EDIT_RGR,
        DELETE_EVENT, GET_GROUPS_BY_FACULTY, GET_ACCOUNT_BY_ID, GET_RGR_BY_INSTRUCTOR }
    [Serializable]
    public class MSG
    {
        public STATUS stat;
    }
}
